services:
  - type: web
    name: chessy-backend
    env: python
    region: oregon # o la región que uses
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn backend.wsgi:application
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: chessy-bdd
          property: connectionString
      # agrega otras variables de entorno que uses acá
    autoDeploy: true
    postDeployCommand: python manage.py migrate
