# Generated by Django 5.2.1 on 2025-05-23 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chessy', '0003_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tournament',
            name='players_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='game',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pendinente'), ('IN_GAME', 'En juego'), ('FINISHED', 'Finalizado')], default='PENDING', max_length=11),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pendiente'), ('IN_PROGRESS', 'En juego'), ('FINISHED', 'Finalizado')], default='PENDING', max_length=11),
        ),
    ]
