# Generated by Django 5.2.1 on 2025-05-23 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chessy', '0004_tournament_description_tournament_players_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pendiente'), ('IN_GAME', 'En juego'), ('FINISHED', 'Finalizado')], default='PENDING', max_length=11),
        ),
    ]
